name = "photography"
compatibility_date = "2026-04-19"
main = "worker/index.ts"

[build]
command = "npm run build && rm -f dist/_redirects"
cwd = "."
watch_dir = "src"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "photography260420"

[images]
binding = "IMAGES"
